from pathlib import Path
import base64,json,html
R=Path(__file__).resolve().parent
D=json.loads((R/'results.json').read_text());C=json.loads((R/'calls.json').read_text())
def image(name,alt):
 data=base64.b64encode((R/'images'/name).read_bytes()).decode()
 return f'<img src="data:image/png;base64,{data}" alt="{alt}">'
def table(headers,rows):
 return '<div class="table"><table><thead><tr>'+''.join('<th>'+html.escape(str(x))+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(x))+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def download(name,label):
 data=base64.b64encode((R/name).read_bytes()).decode()
 return f'<a download="{name}" href="data:application/json;base64,{data}">{label}</a>'
edge=table(['edge_threshold','반영 전: 경계 셀 수','반영 후: 경계 셀 수'],[(t,D['before']['edge'][t],D['after']['edge'][t]) for t in ['0','1','30']])
aa=table(['AA threshold','반영 전: 후보 수','반영 후: 후보 수'],[(t,D['before']['aa'][t],D['after']['aa'][t]) for t in ['0','1','63','64','128','255']])
density=table(['패턴','반영 전 (.25 / .5 / .75)','반영 후 (.25 / .5 / .75)'],[(p,*[' / '.join(str(D[s]['dither'][p][d]['counts'].get('#0000FFFF',0)) for d in ['0.25','0.5','0.75']) for s in ['before','after']]) for p in D['after']['dither']])
body=f'''<header><p class="eyebrow">PIXEL PLUGIN · 검증 보고서 · 2026-09-28</p><h1>MCP #22 반영 전후 비교</h1><p class="lead">같은 조건으로 이전·현재 번들을 실제 실행하고, 저장된 픽셀과 반환 수치를 비교한 결과입니다.</p><div class="summary"><strong>112회 실제 호출 · 비교 단언 통과</strong><span>이전 56회 + 반영 후 56회 · macOS arm64 / Aseprite 1.3.18.2</span></div></header>
<nav aria-label="목차"><a href="#read">읽는 방법</a><a href="#palette">팔레트</a><a href="#density">Density</a><a href="#threshold">Threshold</a><a href="#rare">희소색</a><a href="#scope">스킬·검증 범위</a></nav>
<section id="read"><h2>무엇을 보면 되나요?</h2><p><strong>팔레트 그림의 오른쪽 절반</strong>과 <strong>density 그림의 0.25·0.75 열</strong>을 먼저 보세요. 전자는 사라지던 픽셀이 보존됐는지, 후자는 설정값이 실제 그림에 반영되는지 보여줍니다. Threshold는 후보·경계 수 표로 확인합니다.</p><p>이 보고서는 그림의 미적 품질을 평가하는 자료가 아닙니다. 픽셀 손실 수정, 인자 작동, 기존 기본값 결과 보존을 검사했습니다.</p>{table(['구분','플러그인 커밋','내장 MCP'],[['반영 전','881028f','8d9bdde'],['반영 후','8066c09','bd13cdb']])}</section>
<section id="palette"><p class="tag">01 · 픽셀 손실</p><h2>팔레트를 줄여도 파랑 32픽셀이 유지됩니다</h2><p>8×8 빨강32·파랑32 스프라이트에서 사용하지 않는 팔레트 끝 항목을 제거했습니다. <strong>왼쪽의 회색 체크는 파랑이 사라진 투명 영역</strong>입니다. 반영 후인 오른쪽은 빨강과 파랑 모두 남습니다.</p>{image('palette-comparison.png','팔레트 축소: 이전은 파랑32픽셀이 투명해짐, 이후는 빨강32 파랑32 보존')}{table(['축소 후 결과','반영 전','반영 후'],[['빨강','32픽셀','32픽셀'],['파랑','0픽셀','32픽셀'],['투명','32픽셀','0픽셀'],['투명 mask: 축소 전→후','3→1','255→255']])}<p class="result">판정: 성공 응답만 확인한 것이 아니라, 저장된 파일의 좌표별 색상을 읽어 64픽셀 보존을 확인했습니다.</p><p class="note">이 검사는 미사용 끝 항목 제거에 관한 것입니다. 사용 중인 임의 색상 인덱스를 삭제할 때 자동으로 색을 재배치하거나 모든 편집을 무손실로 처리한다는 뜻은 아닙니다.</p></section>
<section id="density"><p class="tag">02 · 설정값 반영</p><h2>중간 density 값에 따라 실제 픽셀 배치가 달라집니다</h2><p><strong>왼쪽 3열 BEFORE와 오른쪽 3열 AFTER</strong>에서 같은 행·같은 값을 비교하세요. 각 칸 아래 숫자는 64픽셀 중 파랑의 개수입니다.</p><ul><li><strong>Floyd:</strong> 이전에는 .25/.5/.75가 같은 그림이었습니다. 이후에는 값이 커질수록 파랑이 늘어납니다.</li><li><strong>Checker:</strong> 이전 .75는 전부 파랑이었지만, 이후에는 빨강16·파랑48입니다.</li><li><strong>Dots:</strong> .25와 .75에서도 중간 단계가 생겼습니다. .5의 기존 점무늬는 그대로입니다.</li><li><strong>Bayer:</strong> 전후가 같은 것이 정상입니다. 기존 동작의 회귀 확인용입니다.</li></ul>{image('density-comparison.png','네 패턴의 density .25 .5 .75 전후 실제 픽셀 비교')}{density}<p class="result">판정: 4개 패턴 모두 .5의 픽셀 해시가 전후 동일했습니다. 기본값의 색상 수뿐 아니라 실제 배치도 유지됐습니다.</p><p class="note">Density가 모든 패턴에서 정확한 색상 비율을 뜻하지는 않습니다. Floyd .75는 파랑49/64, dots .5는56/64가 이번 실측 결과입니다.</p></section>
<section id="threshold"><p class="tag">03 · 민감도 제어</p><h2>Threshold가 반환 결과를 실제로 바꿉니다</h2><h3>참조 분석: 명시적인 0을 기본값30과 구분</h3><p>좌우 색이 #646464 / #656565인 낮은 대비의 같은 PNG를 분석했습니다. <strong>0 행</strong>을 보세요. 이전에는 기본값30처럼 경계를 놓쳤고, 이후에는 경계12셀을 검출했습니다.</p>{edge}<h3>AA: 대비64인 계단에서 threshold63과64가 달라짐</h3><p>투명 배경에 alpha64 흰색 계단을 그려 <code>auto_apply=false</code>로 분석했습니다. 대비가 threshold보다 <strong>클 때만</strong> 후보를 남기는 계약이므로,63에서는5개·64에서는0개가 맞습니다.</p>{aa}<p class="result">판정: 이전에는 threshold를 바꿔도 AA 후보가 항상5개였지만, 반영 후에는 경계값에서5→0으로 바뀝니다.</p><p class="note">현재 비교는 후보 반환 검사입니다. 전체 AA 탐지 패턴이나 그림 품질을 재설계한 결과가 아닙니다. 실제 apply 및 오류 시 원본 보존은 직전 제어 회귀에서 별도로 검사했습니다.</p></section>
<section id="rare"><p class="tag">04 · 희소색 분석</p><h2>초록 1픽셀을 10회 모두 검출했습니다</h2><p>빨강63픽셀·초록1픽셀인 동일 PNG를 각 버전에서10번씩 분석했습니다. 요청 palette 크기는5입니다.</p>{table(['관찰','반영 전','반영 후'],[['초록을 양의 사용률로 포함','0/10회','10/10회'],['빨강 사용률 합','100%','98.4375%'],['초록 사용률 합','0%','1.5625%'],['반환 palette 항목 수','5','5']])}<p class="result">판정: 이번 작은 입력에서 누락되던 초록을 보존하고 실제 사용률을 반환했습니다.</p><p class="note">반영 후10회 결과는 동일했습니다. 이전10회도 모두 동일한 누락 결과였으므로, 이번 실행에서 이전 버전의 비결정성까지 재현했다고 주장하지 않습니다. 중복·사용률0인 palette 항목은 남을 수 있고, 큰 이미지의 모든 희귀색 보존을 보장하지는 않습니다.</p></section>
<section id="scope"><h2>어떤 경로와 스킬로 검사했나요?</h2><h3>이번 비교: 직접 회귀 검사112회</h3><p>플러그인 wrapper/client → 이전 또는 현재 MCP → 실제 Aseprite 경로를 실행했습니다. 스킬을 자동 실행한 비교는 아닙니다. 이전 바이너리는 기준 커밋에서 추출해 당시 SHA-256과 대조했습니다.</p><p>저장된 native 파일26개를 PNG로 내보내 기존 픽셀 집계와 다시 비교했습니다. 원본 native 바이트는 보존됐습니다. 비교판은 원본8×8 이미지를 정수 배율로 확대했고, 팔레트 그림의 회색 체크만 투명 영역을 설명하기 위한 배경입니다.</p><p>분석용 low.png·rare.png는 두 버전에서 바이트가 같습니다. Native 제작은 같은 픽셀·인자·작업 순서로 실행했으며 native 파일 바이트가 같다고 주장하지 않습니다.</p><h3>직전 동일 후보 검증: 이번112회와 별도</h3>{table(['실행','결과'],[['Codex pixel-art-professional 스킬','실제 MCP12회 성공. reference0/30→12/0, checker .25/.75→빨강/파랑48/16 및16/48. native 독립 검사 일치'],['새 제어 회귀','61회: 성공55·예상 오류6. null/생략, preview/apply, 오류 원본 보존'],['기본·동작·스킬 레시피','7/7 그룹 · 105/105 시나리오 · 8/8 레시피'],['기타 회귀','감색36조합, warnings 성공23/오류3, live37회, export-analysis28회, apple231회·3애니메이션']])}<p class="note">앞선 실행을 이번에 다시 실행한 것으로 합산하지 않았습니다. 설치된 Codex 앱의 자동 연결·GUI, 다른 OS의 native 실행은 미검증입니다.</p></section>
<section><h2>증거 자료</h2><p>원자료의 로컬 절대 경로는 $WORKTREE로 치환했고 수치·픽셀·호출 순서는 유지했습니다. 아래 원자료는 HTML에 내장되어 있습니다. 이 HTML 한 파일만 보관해도 이미지와 원자료를 함께 볼 수 있습니다.</p><p class="downloads">{download('calls.json','호출112회 JSON')}{download('results.json','전후 픽셀·수치 JSON')}{download('provenance.json','버전·checksum JSON')}</p><p>작업: [SHARED][TEST] MCP 리뷰 수정 반영 전후 비교<br>경로: <code>$WORKTREE</code><br>브랜치: <code>fix/shared-mcp-review-sync</code> · 후보 커밋: <code>8066c09</code></p><p>이 보고서 보관 작업은 런타임 코드를 변경하지 않습니다. 2026-09-28 13:30:39 KST 병합 확인 결과 <a href="https://github.com/smrgd88/pixel-plugin/pull/9">플러그인 PR #9</a>는 develop에 MERGED·CI SUCCESS이며 병합 커밋은55c5697입니다. 현재 상태는 PR 링크에서 확인할 수 있습니다.</p></section><footer>실측 결과 중심 보고서 · 원본 PNG26개에서 만든 비교판2개 보관 · 런타임 코드 변경 없음</footer>'''
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#eef2f6;color:#192537;font-family:-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo","Noto Sans KR",sans-serif;line-height:1.75}main{max-width:1100px;margin:40px auto;padding:0 24px}header,section{background:white;border:1px solid #dfe5ec;border-radius:14px;padding:34px;margin-bottom:22px}h1{font-size:36px;line-height:1.3;margin:12px 0}h2{font-size:25px;line-height:1.4;margin-top:0}h3{font-size:19px;margin-top:28px}.eyebrow,.tag{color:#2463a2;font-weight:700;font-size:13px;letter-spacing:.05em}.lead{font-size:18px}.summary{background:#eaf5ee;border-left:4px solid #31845c;padding:16px 20px;margin-top:24px}.summary span{display:block;font-size:14px}nav{display:flex;gap:10px;flex-wrap:wrap;padding:0 0 22px}nav a,.downloads a{background:white;border:1px solid #cbd6e2;border-radius:8px;padding:8px 14px;text-decoration:none;display:inline-block}a{color:#155894}.downloads{display:flex;flex-wrap:wrap;gap:10px}img{display:block;width:100%;height:auto;border:1px solid #e3e8ef;border-radius:8px;margin:22px 0}.table{overflow:auto;margin:20px 0}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;padding:12px 15px;border-bottom:1px solid #dfe5ec;vertical-align:top}th{background:#eef3f8;white-space:nowrap}.result{background:#edf5ff;border-left:4px solid #4084ce;padding:14px 18px}.note{color:#566579;font-size:14px}code{overflow-wrap:anywhere;background:#f0f3f7;padding:2px 5px;border-radius:4px}footer{text-align:center;color:#64748b;font-size:13px;padding:15px 0 30px}section{scroll-margin-top:20px}@media(max-width:640px){main{margin:16px auto;padding:0 12px}header,section{padding:22px 18px}h1{font-size:28px}h2{font-size:22px}th,td{padding:10px;font-size:13px}}@media print{body{background:white}main{max-width:none;margin:0;padding:0}nav{display:none}header,section{border:none;padding:15px 0}h2,h3{break-after:avoid}img,tr{break-inside:avoid}.downloads{display:none}}'''
out='<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MCP #22 반영 전후 비교 보고서</title><style>'+css+'</style></head><body><main>'+body+'</main></body></html>'
(R/'REPORT.html').write_text(out)
from html.parser import HTMLParser
class Check(HTMLParser):
 def __init__(self):super().__init__();self.ids=set();self.anchors=[];self.images=0
 def handle_starttag(self,t,a):
  a=dict(a)
  if 'id'in a:self.ids.add(a['id'])
  if t=='a' and a.get('href','').startswith('#'):self.anchors.append(a['href'][1:])
  if t=='img':
   assert a.get('alt');assert base64.b64decode(a['src'].split(',',1)[1]).startswith(b'\x89PNG');self.images+=1
c=Check();c.feed(out);assert set(c.anchors)<=c.ids and c.images==2
print('PASS: standalone HTML, 2 embedded PNGs, 3 embedded evidence downloads, all internal anchors valid')
